main: testHeuristica1.c
	gcc testHeuristica1.c -o testHeuristica1 -Wall -pedantic -lm

all: main

degub: testHeuristica1.c
	gcc -g testHeuristica1.c -o testHeuristica1 -lm

clean:
	rm testHeuristica1 